name: GlucoseStandby
description: "Glucose Standby"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3
dependencies:
  flutter:
    sdk: flutter

  localpkg_flutter:
    git:
      url: https://github.com/Calebh101/localpkg-flutter-2
      ref: main

  http: ^1.2.2
  intl: ^0.20.0
  uuid: ^4.5.1
  shared_preferences: ^2.3.3
  window_manager: ^0.4.3
  js: ^0.7.1
  universal_html: ^2.2.4
  device_info_plus: ^10.1.2
  url_launcher: ^6.3.1
  wakelock_plus: ^1.2.8
  vibration: ^2.0.1
  google_fonts: ^6.2.1
  audioplayers: ^6.2.0
  flutter_environments_plus: ^1.0.1
  tray_manager: ^0.5.0
  restart_app: ^1.3.2
  fl_chart: ^1.0.0
  dexcom: ^1.0.6
  cupertino_icons: ^1.0.8
  styled_logger: ^1.0.2

  #dexcom:
    #path: /home/caleb/projects/dexcom/dart

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.3

flutter:
  uses-material-design: true

  assets:
    # alerts
    - assets/sounds/alerts/chime.mp3

    # other
    - assets/fonts/
    - assets/app/icon/splash.png
    - assets/app/icon/splash.ico

  fonts:
    - family: DSEG
      fonts:
        - asset: assets/fonts/DSEG14ModernMini-Regular.ttf
          weight: 700
    - family: Exo
      fonts:
        - asset: assets/fonts/Exo-Regular.ttf
          weight: 700
    - family: Audiowide
      fonts:
        - asset: assets/fonts/Audiowide-Regular.ttf
          weight: 700
