name: GlucoseStandby
description: "Glucose Standby"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3
dependencies:
  flutter:
    sdk: flutter

  localpkg_flutter:
    git:
      url: https://github.com/Calebh101/localpkg-flutter-2
      ref: bfe95d1576f084f95bc1cb06b31a22a3b02fba33

  http: ^1.6.0
  intl: ^0.20.2
  shared_preferences: ^2.5.4
  window_manager: ^0.5.1
  universal_html: ^2.3.0
  wakelock_plus: ^1.4.0
  google_fonts: ^6.3.3
  flutter_environments_plus: ^1.0.1
  tray_manager: ^0.5.2
  restart_app: ^1.3.2
  styled_logger: ^1.0.2
  settings_ui: ^2.0.2
  flutter_window_close: ^1.3.0

  # Debug
  dexcom:
    path: /home/caleb/projects/other/dexcom/dart

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.3

flutter:
  uses-material-design: true

  assets:
    # Alert sound effects
    - assets/sounds/alerts/chime.mp3

    # Fonts
    - assets/fonts/

    # Icons
    - assets/app/icon/splash.png
    - assets/app/icon/splash.ico

  fonts:
    - family: DSEG
      fonts:
        - asset: assets/fonts/DSEG14ModernMini-Regular.ttf
          weight: 700
    - family: Exo
      fonts:
        - asset: assets/fonts/Exo-Regular.ttf
          weight: 700
    - family: Audiowide
      fonts:
        - asset: assets/fonts/Audiowide-Regular.ttf
          weight: 700
